# Type, name and class can be strings like "LGBModel" or can be objects like LGBModel
# Do not worry about data-types, the framework will handle them

methods:
  - type: "FSMethodExperiment"
    name: "Boruta"
    model_hyperparameters:
      random_state: 0
    num_bag_folds: 8
    time_limit: 3600

  - type: "FSMethodExperiment"
    name: "LS_Flip"
    model_hyperparameters:
      random_state: 0
    num_bag_folds: 8
    time_limit: 3600